import type { IngredientRecord, RecipeDefinition, SubRecipeDefinition } from "./types";

const DEFAULT_TARGET_MARGIN = 0.7;
const DEFAULT_TAX = 0.21;
const DEFAULT_TIMESTAMP = "2026-06-03T00:00:00.000Z";

export const supplierSeed = [
  {
    id: "s1",
    name: "Carnes Benny",
    contact: null,
    phone: null,
    leadTimeDays: 2,
    active: true,
    notes: "Blend de carne y bacon",
    createdAt: DEFAULT_TIMESTAMP,
    updatedAt: DEFAULT_TIMESTAMP,
  },
  {
    id: "s2",
    name: "Panificados Benny",
    contact: null,
    phone: null,
    leadTimeDays: 1,
    active: true,
    notes: "Panes, papas y descartables",
    createdAt: DEFAULT_TIMESTAMP,
    updatedAt: DEFAULT_TIMESTAMP,
  },
  {
    id: "s3",
    name: "Verdulería Benny",
    contact: null,
    phone: null,
    leadTimeDays: 1,
    active: true,
    notes: "Cebolla, tomate, lechuga y champiñones",
    createdAt: DEFAULT_TIMESTAMP,
    updatedAt: DEFAULT_TIMESTAMP,
  },
  {
    id: "s4",
    name: "Lácteos Benny",
    contact: null,
    phone: null,
    leadTimeDays: 2,
    active: true,
    notes: "Cheddar, dambo y queso azul",
    createdAt: DEFAULT_TIMESTAMP,
    updatedAt: DEFAULT_TIMESTAMP,
  },
  {
    id: "s5",
    name: "Almacén Benny",
    contact: null,
    phone: null,
    leadTimeDays: 2,
    active: true,
    notes: "Aderezos y snacks",
    createdAt: DEFAULT_TIMESTAMP,
    updatedAt: DEFAULT_TIMESTAMP,
  },
  {
    id: "s6",
    name: "Delivery Benny",
    contact: null,
    phone: null,
    leadTimeDays: 0,
    active: true,
    notes: "Costo operativo de delivery",
    createdAt: DEFAULT_TIMESTAMP,
    updatedAt: DEFAULT_TIMESTAMP,
  },
] as const;

export const ingredientSupplierMap: Record<string, string> = {
  blend: "s1",
  pan: "s2",
  cheddar: "s4",
  papelAluminio: "s2",
  bolsaPapel: "s2",
  cajitaHamburguesa: "s2",
  cajitaPapas: "s2",
  papasCombo: "s2",
  bacon: "s1",
  cebolla: "s3",
  aderesos: "s5",
  delivery: "s6",
  tomate: "s3",
  lechuga: "s3",
  dambo: "s4",
  quesoAzul: "s4",
  champinones: "s3",
  doritos: "s5",
};

export const ingredientCategoryMap: Record<string, string> = {
  blend: "Carnes",
  pan: "Panificados",
  cheddar: "Lácteos",
  papelAluminio: "Packaging",
  bolsaPapel: "Packaging",
  cajitaHamburguesa: "Packaging",
  cajitaPapas: "Packaging",
  papasCombo: "Acompañamientos",
  bacon: "Carnes",
  cebolla: "Verduras",
  aderesos: "Almacén",
  delivery: "Operación",
  tomate: "Verduras",
  lechuga: "Verduras",
  dambo: "Lácteos",
  quesoAzul: "Lácteos",
  champinones: "Verduras",
  doritos: "Almacén",
};

export const ingredientSkus: Record<string, string | undefined> = {
  blend: "BEN-CAR-001",
  pan: "BEN-PAN-001",
  cheddar: "BEN-LAC-001",
  papelAluminio: "BEN-PKG-001",
  bolsaPapel: "BEN-PKG-002",
  cajitaHamburguesa: "BEN-PKG-003",
  cajitaPapas: "BEN-PKG-004",
  papasCombo: "BEN-PAP-001",
  bacon: "BEN-CAR-002",
  cebolla: "BEN-VER-001",
  aderesos: "BEN-ALM-001",
  delivery: undefined,
  tomate: "BEN-VER-002",
  lechuga: "BEN-VER-003",
  dambo: "BEN-LAC-002",
  quesoAzul: "BEN-LAC-003",
  champinones: "BEN-VER-004",
  doritos: "BEN-ALM-002",
};

export const ingredientSeed: Record<string, IngredientRecord> = {
  blend: {
    id: "blend",
    name: "Blend de Carne",
    purchasePrice: 1400,
    purchaseQuantity: 1,
    purchaseUnit: "u",
    usageUnit: "u",
    minDailyConsumption: 18,
    maxDailyConsumption: 36,
    currentStock: 24,
  },
  pan: {
    id: "pan",
    name: "Pan",
    purchasePrice: 500,
    purchaseQuantity: 1,
    purchaseUnit: "u",
    usageUnit: "u",
    minDailyConsumption: 14,
    maxDailyConsumption: 28,
    currentStock: 18,
  },
  cheddar: {
    id: "cheddar",
    name: "Cheddar",
    purchasePrice: 180,
    purchaseQuantity: 1,
    purchaseUnit: "u",
    usageUnit: "u",
    minDailyConsumption: 24,
    maxDailyConsumption: 48,
    currentStock: 22,
  },
  papelAluminio: {
    id: "papelAluminio",
    name: "Papel Aluminio",
    purchasePrice: 250,
    purchaseQuantity: 1,
    purchaseUnit: "u",
    usageUnit: "u",
    minDailyConsumption: 12,
    maxDailyConsumption: 24,
    currentStock: 14,
  },
  bolsaPapel: {
    id: "bolsaPapel",
    name: "Bolsa Papel",
    purchasePrice: 150,
    purchaseQuantity: 1,
    purchaseUnit: "u",
    usageUnit: "u",
    minDailyConsumption: 12,
    maxDailyConsumption: 24,
    currentStock: 10,
  },
  cajitaHamburguesa: {
    id: "cajitaHamburguesa",
    name: "Cajita Hamburguesa",
    purchasePrice: 215,
    purchaseQuantity: 1,
    purchaseUnit: "u",
    usageUnit: "u",
    minDailyConsumption: 8,
    maxDailyConsumption: 16,
    currentStock: 10,
  },
  cajitaPapas: {
    id: "cajitaPapas",
    name: "Cajita Papas",
    purchasePrice: 97,
    purchaseQuantity: 1,
    purchaseUnit: "u",
    usageUnit: "u",
    minDailyConsumption: 10,
    maxDailyConsumption: 20,
    currentStock: 8,
  },
  papasCombo: {
    id: "papasCombo",
    name: "Papas (incluye  Caja)",
    purchasePrice: 750,
    purchaseQuantity: 1,
    purchaseUnit: "u",
    usageUnit: "u",
    minDailyConsumption: 10,
    maxDailyConsumption: 20,
    currentStock: 6,
  },
  bacon: {
    id: "bacon",
    name: "Bacon",
    purchasePrice: 320,
    purchaseQuantity: 1,
    purchaseUnit: "u",
    usageUnit: "u",
    minDailyConsumption: 8,
    maxDailyConsumption: 16,
    currentStock: 6,
  },
  cebolla: {
    id: "cebolla",
    name: "Cebolla",
    purchasePrice: 100,
    purchaseQuantity: 1,
    purchaseUnit: "u",
    usageUnit: "u",
    minDailyConsumption: 8,
    maxDailyConsumption: 16,
    currentStock: 10,
  },
  aderesos: {
    id: "aderesos",
    name: "Aderesos",
    purchasePrice: 200,
    purchaseQuantity: 1,
    purchaseUnit: "u",
    usageUnit: "u",
    minDailyConsumption: 10,
    maxDailyConsumption: 20,
    currentStock: 8,
  },
  delivery: {
    id: "delivery",
    name: "Delivery",
    purchasePrice: 2000,
    purchaseQuantity: 1,
    purchaseUnit: "u",
    usageUnit: "u",
    minDailyConsumption: 0,
    maxDailyConsumption: 0,
    currentStock: 0,
  },
  tomate: {
    id: "tomate",
    name: "Tomate (50 gr)",
    purchasePrice: 200,
    purchaseQuantity: 1,
    purchaseUnit: "u",
    usageUnit: "u",
    minDailyConsumption: 6,
    maxDailyConsumption: 12,
    currentStock: 8,
  },
  lechuga: {
    id: "lechuga",
    name: "Lechuga (20 gr)",
    purchasePrice: 100,
    purchaseQuantity: 1,
    purchaseUnit: "u",
    usageUnit: "u",
    minDailyConsumption: 6,
    maxDailyConsumption: 12,
    currentStock: 8,
  },
  dambo: {
    id: "dambo",
    name: "Dambo",
    purchasePrice: 180,
    purchaseQuantity: 1,
    purchaseUnit: "u",
    usageUnit: "u",
    minDailyConsumption: 12,
    maxDailyConsumption: 24,
    currentStock: 16,
  },
  quesoAzul: {
    id: "quesoAzul",
    name: "Queso Azul",
    purchasePrice: 170,
    purchaseQuantity: 1,
    purchaseUnit: "u",
    usageUnit: "u",
    minDailyConsumption: 8,
    maxDailyConsumption: 16,
    currentStock: 10,
  },
  champinones: {
    id: "champinones",
    name: "Champiñones",
    purchasePrice: 770,
    purchaseQuantity: 1,
    purchaseUnit: "u",
    usageUnit: "u",
    minDailyConsumption: 3,
    maxDailyConsumption: 8,
    currentStock: 4,
  },
  doritos: {
    id: "doritos",
    name: "Doritos (porcion 12gr)",
    purchasePrice: 380,
    purchaseQuantity: 1,
    purchaseUnit: "u",
    usageUnit: "u",
    minDailyConsumption: 2,
    maxDailyConsumption: 8,
    currentStock: 3,
  },
};

export const subRecipeSeed: Record<string, SubRecipeDefinition> = {
  cebollaCaramelizada: {
    id: "cebollaCaramelizada",
    name: "Cebolla Caramelizada",
    outputQuantity: 1,
    outputUnit: "u",
    lines: [{ id: "sub-cebolla-caramelizada-1", type: "ingredient", ingredientId: "cebolla", quantity: 3, unit: "u" }],
  },
};

export const recipeSeed: RecipeDefinition[] = [
  {
    id: "benny-cheez-simple",
    name: "Benny Cheez Simple",
    servings: 1,
    targetMarginPct: DEFAULT_TARGET_MARGIN,
    currentSalePrice: 8700,
    taxPct: DEFAULT_TAX,
    lines: [
      { id: "bcs-1", type: "ingredient", ingredientId: "blend", quantity: 1, unit: "u" },
      { id: "bcs-2", type: "ingredient", ingredientId: "cheddar", quantity: 2, unit: "u" },
      { id: "bcs-3", type: "ingredient", ingredientId: "pan", quantity: 1, unit: "u" },
      { id: "bcs-4", type: "ingredient", ingredientId: "aderesos", quantity: 1, unit: "u" },
      { id: "bcs-5", type: "ingredient", ingredientId: "papelAluminio", quantity: 1, unit: "u" },
      { id: "bcs-6", type: "ingredient", ingredientId: "bolsaPapel", quantity: 1, unit: "u" },
      { id: "bcs-7", type: "ingredient", ingredientId: "papasCombo", quantity: 1, unit: "u" },
    ],
  },
  {
    id: "benny-cheez-doble",
    name: "Benny Cheez Doble",
    servings: 1,
    targetMarginPct: DEFAULT_TARGET_MARGIN,
    currentSalePrice: 10500,
    taxPct: DEFAULT_TAX,
    lines: [
      { id: "bcd-1", type: "ingredient", ingredientId: "blend", quantity: 2, unit: "u" },
      { id: "bcd-2", type: "ingredient", ingredientId: "cheddar", quantity: 3, unit: "u" },
      { id: "bcd-3", type: "ingredient", ingredientId: "pan", quantity: 1, unit: "u" },
      { id: "bcd-4", type: "ingredient", ingredientId: "aderesos", quantity: 1, unit: "u" },
      { id: "bcd-5", type: "ingredient", ingredientId: "papelAluminio", quantity: 1, unit: "u" },
      { id: "bcd-6", type: "ingredient", ingredientId: "bolsaPapel", quantity: 1, unit: "u" },
      { id: "bcd-7", type: "ingredient", ingredientId: "papasCombo", quantity: 1, unit: "u" },
    ],
  },
  {
    id: "benny-cheez-triple",
    name: "Benny Cheez Triple",
    servings: 1,
    targetMarginPct: DEFAULT_TARGET_MARGIN,
    currentSalePrice: 13700,
    taxPct: DEFAULT_TAX,
    lines: [
      { id: "bct-1", type: "ingredient", ingredientId: "blend", quantity: 3, unit: "u" },
      { id: "bct-2", type: "ingredient", ingredientId: "cheddar", quantity: 4, unit: "u" },
      { id: "bct-3", type: "ingredient", ingredientId: "pan", quantity: 1, unit: "u" },
      { id: "bct-4", type: "ingredient", ingredientId: "aderesos", quantity: 1, unit: "u" },
      { id: "bct-5", type: "ingredient", ingredientId: "papelAluminio", quantity: 1, unit: "u" },
      { id: "bct-6", type: "ingredient", ingredientId: "bolsaPapel", quantity: 1, unit: "u" },
      { id: "bct-7", type: "ingredient", ingredientId: "papasCombo", quantity: 1, unit: "u" },
    ],
  },
  {
    id: "retro-simple",
    name: "Retro Simple",
    servings: 1,
    targetMarginPct: DEFAULT_TARGET_MARGIN,
    currentSalePrice: 9400,
    taxPct: DEFAULT_TAX,
    lines: [
      { id: "rs-1", type: "ingredient", ingredientId: "blend", quantity: 1, unit: "u" },
      { id: "rs-2", type: "ingredient", ingredientId: "dambo", quantity: 2, unit: "u" },
      { id: "rs-3", type: "ingredient", ingredientId: "pan", quantity: 1, unit: "u" },
      { id: "rs-4", type: "ingredient", ingredientId: "aderesos", quantity: 1, unit: "u" },
      { id: "rs-5", type: "ingredient", ingredientId: "tomate", quantity: 1, unit: "u" },
      { id: "rs-6", type: "ingredient", ingredientId: "lechuga", quantity: 1, unit: "u" },
      { id: "rs-7", type: "ingredient", ingredientId: "papelAluminio", quantity: 1, unit: "u" },
      { id: "rs-8", type: "ingredient", ingredientId: "bolsaPapel", quantity: 1, unit: "u" },
      { id: "rs-9", type: "ingredient", ingredientId: "papasCombo", quantity: 1, unit: "u" },
    ],
  },
  {
    id: "retro-doble",
    name: "Retro Doble",
    servings: 1,
    targetMarginPct: DEFAULT_TARGET_MARGIN,
    currentSalePrice: 11500,
    taxPct: DEFAULT_TAX,
    lines: [
      { id: "rd-1", type: "ingredient", ingredientId: "blend", quantity: 2, unit: "u" },
      { id: "rd-2", type: "ingredient", ingredientId: "dambo", quantity: 3, unit: "u" },
      { id: "rd-3", type: "ingredient", ingredientId: "pan", quantity: 1, unit: "u" },
      { id: "rd-4", type: "ingredient", ingredientId: "aderesos", quantity: 1, unit: "u" },
      { id: "rd-5", type: "ingredient", ingredientId: "tomate", quantity: 1, unit: "u" },
      { id: "rd-6", type: "ingredient", ingredientId: "lechuga", quantity: 1, unit: "u" },
      { id: "rd-7", type: "ingredient", ingredientId: "papelAluminio", quantity: 1, unit: "u" },
      { id: "rd-8", type: "ingredient", ingredientId: "bolsaPapel", quantity: 1, unit: "u" },
      { id: "rd-9", type: "ingredient", ingredientId: "papasCombo", quantity: 1, unit: "u" },
    ],
  },
  {
    id: "full-benny-simple",
    name: "Full Benny Simple",
    servings: 1,
    targetMarginPct: DEFAULT_TARGET_MARGIN,
    currentSalePrice: 9700,
    taxPct: DEFAULT_TAX,
    lines: [
      { id: "fbs-1", type: "ingredient", ingredientId: "blend", quantity: 1, unit: "u" },
      { id: "fbs-2", type: "ingredient", ingredientId: "cheddar", quantity: 2, unit: "u" },
      { id: "fbs-3", type: "ingredient", ingredientId: "pan", quantity: 1, unit: "u" },
      { id: "fbs-4", type: "ingredient", ingredientId: "bacon", quantity: 1, unit: "u" },
      { id: "fbs-5", type: "ingredient", ingredientId: "cebolla", quantity: 2, unit: "u" },
      { id: "fbs-6", type: "ingredient", ingredientId: "aderesos", quantity: 1, unit: "u" },
      { id: "fbs-7", type: "ingredient", ingredientId: "papelAluminio", quantity: 1, unit: "u" },
      { id: "fbs-8", type: "ingredient", ingredientId: "bolsaPapel", quantity: 1, unit: "u" },
      { id: "fbs-9", type: "ingredient", ingredientId: "papasCombo", quantity: 1, unit: "u" },
    ],
  },
  {
    id: "full-benny-doble",
    name: "Full Benny Doble",
    servings: 1,
    targetMarginPct: DEFAULT_TARGET_MARGIN,
    currentSalePrice: 12800,
    taxPct: DEFAULT_TAX,
    lines: [
      { id: "fbd-1", type: "ingredient", ingredientId: "blend", quantity: 2, unit: "u" },
      { id: "fbd-2", type: "ingredient", ingredientId: "cheddar", quantity: 3, unit: "u" },
      { id: "fbd-3", type: "ingredient", ingredientId: "pan", quantity: 1, unit: "u" },
      { id: "fbd-4", type: "ingredient", ingredientId: "bacon", quantity: 2, unit: "u" },
      { id: "fbd-5", type: "ingredient", ingredientId: "cebolla", quantity: 2, unit: "u" },
      { id: "fbd-6", type: "ingredient", ingredientId: "aderesos", quantity: 1, unit: "u" },
      { id: "fbd-7", type: "ingredient", ingredientId: "papelAluminio", quantity: 1, unit: "u" },
      { id: "fbd-8", type: "ingredient", ingredientId: "bolsaPapel", quantity: 1, unit: "u" },
      { id: "fbd-9", type: "ingredient", ingredientId: "papasCombo", quantity: 1, unit: "u" },
    ],
  },
  {
    id: "benny-fort-simple",
    name: "Benny Fort Simple",
    servings: 1,
    targetMarginPct: DEFAULT_TARGET_MARGIN,
    currentSalePrice: 9900,
    taxPct: DEFAULT_TAX,
    lines: [
      { id: "bfs-1", type: "ingredient", ingredientId: "blend", quantity: 1, unit: "u" },
      { id: "bfs-2", type: "ingredient", ingredientId: "quesoAzul", quantity: 2, unit: "u" },
      { id: "bfs-3", type: "ingredient", ingredientId: "champinones", quantity: 1, unit: "u" },
      { id: "bfs-4", type: "ingredient", ingredientId: "pan", quantity: 1, unit: "u" },
      { id: "bfs-5", type: "ingredient", ingredientId: "aderesos", quantity: 1, unit: "u" },
      { id: "bfs-6", type: "ingredient", ingredientId: "papelAluminio", quantity: 1, unit: "u" },
      { id: "bfs-7", type: "ingredient", ingredientId: "bolsaPapel", quantity: 1, unit: "u" },
      { id: "bfs-8", type: "ingredient", ingredientId: "papasCombo", quantity: 1, unit: "u" },
    ],
  },
  {
    id: "benny-fort-doble",
    name: "Benny Fort Doble",
    servings: 1,
    targetMarginPct: DEFAULT_TARGET_MARGIN,
    currentSalePrice: 12800,
    taxPct: DEFAULT_TAX,
    lines: [
      { id: "bfd-1", type: "ingredient", ingredientId: "blend", quantity: 2, unit: "u" },
      { id: "bfd-2", type: "ingredient", ingredientId: "quesoAzul", quantity: 3, unit: "u" },
      { id: "bfd-3", type: "ingredient", ingredientId: "champinones", quantity: 1, unit: "u" },
      { id: "bfd-4", type: "ingredient", ingredientId: "pan", quantity: 2, unit: "u" },
      { id: "bfd-5", type: "ingredient", ingredientId: "aderesos", quantity: 2, unit: "u" },
      { id: "bfd-6", type: "ingredient", ingredientId: "papelAluminio", quantity: 1, unit: "u" },
      { id: "bfd-7", type: "ingredient", ingredientId: "bolsaPapel", quantity: 1, unit: "u" },
      { id: "bfd-8", type: "ingredient", ingredientId: "papasCombo", quantity: 1, unit: "u" },
    ],
  },
  {
    id: "benny-doro",
    name: "Benny D'oro Simple",
    servings: 1,
    targetMarginPct: DEFAULT_TARGET_MARGIN,
    currentSalePrice: 10200,
    taxPct: DEFAULT_TAX,
    lines: [
      { id: "bdo-1", type: "ingredient", ingredientId: "blend", quantity: 1, unit: "u" },
      { id: "bdo-2", type: "ingredient", ingredientId: "cheddar", quantity: 2, unit: "u" },
      { id: "bdo-3", type: "subRecipe", subRecipeId: "cebollaCaramelizada", quantity: 1, unit: "u" },
      { id: "bdo-4", type: "ingredient", ingredientId: "bacon", quantity: 1, unit: "u" },
      { id: "bdo-5", type: "ingredient", ingredientId: "doritos", quantity: 1, unit: "u" },
      { id: "bdo-6", type: "ingredient", ingredientId: "pan", quantity: 1, unit: "u" },
      { id: "bdo-7", type: "ingredient", ingredientId: "papelAluminio", quantity: 1, unit: "u" },
      { id: "bdo-8", type: "ingredient", ingredientId: "papasCombo", quantity: 1, unit: "u" },
      { id: "bdo-9", type: "ingredient", ingredientId: "bolsaPapel", quantity: 1, unit: "u" },
      { id: "bdo-10", type: "ingredient", ingredientId: "aderesos", quantity: 1, unit: "u" },
    ],
  },
  {
    id: "benny-doro-doble",
    name: "Benny D'oro Doble",
    servings: 1,
    targetMarginPct: DEFAULT_TARGET_MARGIN,
    currentSalePrice: 13100,
    taxPct: DEFAULT_TAX,
    lines: [
      { id: "bdod-1", type: "ingredient", ingredientId: "blend", quantity: 2, unit: "u" },
      { id: "bdod-2", type: "ingredient", ingredientId: "cheddar", quantity: 3, unit: "u" },
      { id: "bdod-3", type: "subRecipe", subRecipeId: "cebollaCaramelizada", quantity: 1, unit: "u" },
      { id: "bdod-4", type: "ingredient", ingredientId: "bacon", quantity: 2, unit: "u" },
      { id: "bdod-5", type: "ingredient", ingredientId: "doritos", quantity: 1, unit: "u" },
      { id: "bdod-6", type: "ingredient", ingredientId: "pan", quantity: 1, unit: "u" },
      { id: "bdod-7", type: "ingredient", ingredientId: "papelAluminio", quantity: 1, unit: "u" },
      { id: "bdod-8", type: "ingredient", ingredientId: "papasCombo", quantity: 1, unit: "u" },
      { id: "bdod-9", type: "ingredient", ingredientId: "bolsaPapel", quantity: 1, unit: "u" },
      { id: "bdod-10", type: "ingredient", ingredientId: "aderesos", quantity: 1, unit: "u" },
    ],
  },
];
